apiVersion: apps/v1
kind: Deployment
metadata:
  name: estudiantesnet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: estudiantesnet-api

  template:
    metadata:
      labels:
        app: estudiantesnet-api

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: estudiantesnet-api
          image: ghcr.io/zuyto/estudiantesnet-api:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"

          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20